            - name: Notify Teams
  # You may pin to the exact commit or the version.
  # uses: thechetantalwar/teams-notify@8a78811f5e8f58cdd204efebd79158006428c46b
  uses: thechetantalwar/teams-notify@v2
  with:
    # WebHook URL of your MS Teams Channel
    teams_webhook_url: "https://prod-32.westeurope.logic.azure.com:443/workflows/7c315275e2ca43c1a516b520dc5740ef/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=ATOvQUq8WxEl01HLP66vuXx6Tt2kfgYMTbVu4TaDqLs"
    # Message to be sent
    message: "Hi ! How are you buddy"
          
