name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build TodoApp.csproj --no-restore
        
    continue-on-error: true

  test:
    runs-on: ubuntu-latest
    needs: build
    if: always()

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Test
        run: dotnet test TodoApp.Tests/TodoApp.Tests.csproj --no-build --verbosity normal

      - name: Send a Notification
        id: notify
        uses: thechetantalwar/teams-notify@v2
        with:
          teams_webhook_url: 'https://solo.requestcatcher.com/test'
          message: "Github Action Build Number dont know."

      - name: Notify Teams
        uses: thechetantalwar/teams-notify@v2
        with:
          # WebHook URL of your MS Teams Channel
          teams_webhook_url: 'https://prod-199.westeurope.logic.azure.com:443/workflows/9539a516954648158c307dc25e938a89/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=n--13NTV3EKuhMDgK5-8detaaGq_KrZsLMNx_ibkYPo'
          #teams_webhook_url: 'https://prod-32.westeurope.logic.azure.com:443/workflows/7c315275e2ca43c1a516b520dc5740ef/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=ATOvQUq8WxEl01HLP66vuXx6Tt2kfgYMTbVu4TaDqLs'
          # Message to be sent
          #teams_webhook_url: 'https://bob.requestcatcher.com/test'
          message: Hi ! How are you buddy
