name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: always()

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Test
        run: dotnet test TodoApp.Tests/TodoApp.Tests.csproj --no-build --verbosity normal
        
      - name: Send a Notification
        id: notify
        uses: thechetantalwar/teams-notify@v2
        with:
          teams_webhook_url: 'https://headd.requestcatcher.com/test'
          message: "Github Action Build Number dont know."

      - name: Notify Teams
        uses: thechetantalwar/teams-notify@v2
        with:
          # WebHook URL of your MS Teams Channel
          #teams_webhook_url: 'https://prod-199.westeurope.logic.azure.com:443/workflows/9539a516954648158c307dc25e938a89/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=n--13NTV3EKuhMDgK5-8detaaGq_KrZsLMNx_ibkYPo'
          # Message to be sent
          teams_webhook_url: 'https://prod-06.westeurope.logic.azure.com:443/workflows/e6d4754a597744c8927160e4ecb9d957/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=Cf-lIR_zs_aVo0BEDj-E4SQuoJU5NUuzw_uXYX6seEQ'
          message: "Hi! How are you buddy?"
